remedial2/home/urls.py
from django.urls import path




from home import views


app_name = "home"

urlpatterns = [
    path('', views.Index.as_view(), name="index"),
]

remedial2/nfl/urls.py
from django.urls import path
from . import views

app_name = 'nfl' 

urlpatterns = [
    path('duenio/create/', views.CreateDuenio.as_view(), name='create_duenio'),
    path('duenio/list/', views.ListDuenios.as_view(), name='list_duenio'),
    path('duenio/<int:pk>/', views.DetailDuenio.as_view(), name='detail_duenio'),
    path('duenio/<int:pk>/update/', views.UpdateDuenio.as_view(), name='update_duenio'),
    path('duenio/<int:pk>/delete/', views.DeleteDuenio.as_view(), name='delete_duenio'),

    # URLs para Ciudad
    path('ciudad/create/', views.CreateCiudad.as_view(), name='create_ciudad'),
    path('ciudad/list/', views.ListCiudades.as_view(), name='list_ciudades'),
    path('ciudad/<int:pk>/', views.DetailCiudad.as_view(), name='detail_ciudad'),
    path('ciudad/update/<int:pk>/', views.UpdateCiudad.as_view(), name='update_ciudad'),
    path('ciudad/<int:pk>/delete/', views.DeleteCiudad.as_view(), name='delete_ciudad'),

    # URLs para Equipo
    path('equipo/create/', views.CreateEquipo.as_view(), name='create_equipo'),
    path('equipo/list/', views.ListEquipos.as_view(), name='list_equipo'),
    path('equipo/<int:pk>/', views.DetailEquipo.as_view(), name='detail_equipo'),
    path('equipo/<int:pk>/update/', views.UpdateEquipo.as_view(), name='update_equipo'),
    path('equipo/<int:pk>/delete/', views.DeleteEquipo.as_view(), name='delete_equipo'),

    # URLs para Estadio
    path('estadio/create/', views.CreateEstadio.as_view(), name='create_estadio'),
    path('estadio/list/', views.ListEstadios.as_view(), name='list_estadio'),
    path('estadio/<int:pk>/', views.DetailEstadio.as_view(), name='detail_estadio'),
    path('estadio/<int:pk>/update/', views.UpdateEstadio.as_view(), name='update_estadio'),
    path('estadio/<int:pk>/delete/', views.DeleteEstadio.as_view(), name='delete_estadio'),

    # URLs para Jugador
    path('jugador/create/', views.CreateJugador.as_view(), name='create_jugador'),
    path('jugador/list/', views.ListJugadores.as_view(), name='list_jugador'),
    path('jugador/<int:pk>/', views.DetailJugador.as_view(), name='detail_jugador'),
    path('jugador/<int:pk>/update/', views.UpdateJugador.as_view(), name='update_jugador'),
    path('jugador/<int:pk>/delete/', views.DeleteJugador.as_view(), name='delete_jugador'),
]

remedial2/nfl_app/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('nfl/', include('nfl.urls')),
]

remedial2/nfl/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from datetime import timedelta

# Create your models here.
class Duenio(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre
    
class Ciudad(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre


class Equipo(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=100)
    ciudad = models.ForeignKey(Ciudad, on_delete=models.CASCADE)
    duenio = models.ForeignKey(Duenio, on_delete=models.CASCADE)
    def __str__(self):
        return self.nombre

class Estadio(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=100)
    equipo = models.ForeignKey(Equipo, on_delete=models.CASCADE)
    duenio = models.ForeignKey(Duenio, on_delete=models.CASCADE)
    capacidad = models.CharField(max_length=30)
    size = models.CharField(max_length=20)

    def __str__(self):
        return self.nombre
    
class Jugador(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=100)
    equipo = models.ForeignKey(Equipo, on_delete=models.CASCADE)
    posicion = models.CharField(max_length=15)
    numero = models.CharField(max_length=10)

    
 
 
 

remedial2/nfl/forms.py
from django import forms
from .models import Ciudad, Equipo, Estadio,Duenio, Jugador

class CiudadForm(forms.ModelForm):
    class Meta:
        model = Ciudad
        fields = ["nombre"]
        widgets = {
            "nombre": forms.TextInput(attrs={"class": "form-control", "placeholder": "Nombre de la ciudad"}),
        }

class EquipoForm(forms.ModelForm):
    class Meta:
        model = Equipo
        fields = ["nombre", "ciudad", "duenio"]  
        widgets = {
            "nombre": forms.TextInput(attrs={"class": "form-control", "placeholder": "Nombre del equipo"}),
            "ciudad": forms.Select(attrs={"class": "form-control"}),
            "duenio": forms.Select(attrs={"class": "form-control"}),  
        }

class EstadioForm(forms.ModelForm):
    class Meta:
        model = Estadio
        fields = ["nombre", "equipo", "duenio","capacidad","size"]  
        widgets = {
            "nombre": forms.TextInput(attrs={"class": "form-control", "placeholder": "Nombre del estadio"}),
            "equipo": forms.Select(attrs={"class": "form-control"}),
            "duenio": forms.Select(attrs={"class": "form-control"}),  
            "capacidad": forms.TextInput(attrs={"class": "form-control"}),
            "size": forms.TextInput(attrs={"class": "form-control"}),
        }

class JugadorForm(forms.ModelForm):
    class Meta:
        model = Jugador
        fields = ["nombre", "equipo","numero","posicion"]
        widgets = {
            "nombre": forms.TextInput(attrs={"class": "form-control", "placeholder": "Nombre del jugador"}),
            "equipo": forms.Select(attrs={"class": "form-control"}),
            "numero": forms.TextInput(attrs={"class": "form-control"}),
            "posicion": forms.TextInput(attrs={"class": "form-control"}),
        }

class DuenioForm(forms.ModelForm):
    class Meta:
        model = Duenio
        fields = ["nombre"]
        widgets = {
            "nombre": forms.TextInput(attrs={"class": "form-control", "placeholder": "Nombre del dueño"}),
        }

remedial2/nfl/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.urls import reverse_lazy
from .forms import CiudadForm, EquipoForm, EstadioForm, DuenioForm, JugadorForm
from .models import Ciudad, Equipo, Estadio, Duenio, Jugador
# Vistas para Ciudad
class CreateCiudad(CreateView):
    template_name = "nfl/create_ciudad.html"
    model = Ciudad
    form_class = CiudadForm
    success_url = reverse_lazy('nfl:list_ciudades')

class ListCiudades(ListView):
    template_name = "nfl/list_ciudades.html"  
    model = Ciudad
    context_object_name = 'ciudades'

class DetailCiudad(DetailView):
    template_name = "nfl/detail_ciudad.html"
    model = Ciudad
    context_object_name = 'ciudad'

class UpdateCiudad(UpdateView):
    template_name = "nfl/update_ciudad.html"
    model = Ciudad
    form_class = CiudadForm
    success_url = reverse_lazy('nfl:list_ciudades')

class DeleteCiudad(DeleteView):
    template_name = "nfl/delete_ciudad.html"
    model = Ciudad
    success_url = reverse_lazy('nfl:list_ciudades')

# Vistas para Equipo
class CreateEquipo(CreateView):
    template_name = "nfl/create_equipo.html"
    model = Equipo
    form_class = EquipoForm
    success_url = reverse_lazy('nfl:list_equipo')

class ListEquipos(ListView):
    template_name = "nfl/list_equipo.html"
    model = Equipo
    context_object_name = 'equipos'

class DetailEquipo(DetailView):
    template_name = "nfl/detail_equipo.html"
    model = Equipo
    context_object_name = 'equipo'

class UpdateEquipo(UpdateView):
    template_name = "nfl/update_equipo.html"
    model = Equipo
    form_class = EquipoForm
    success_url = reverse_lazy('nfl:list_equipo')

class DeleteEquipo(DeleteView):
    template_name = "nfl/delete_equipo.html"
    model = Equipo
    success_url = reverse_lazy('nfl:list_equipo')


# Vistas para Estadio
class CreateEstadio(CreateView):
    template_name = "nfl/create_estadio.html"
    model = Estadio
    form_class = EstadioForm
    success_url = reverse_lazy('nfl:list_estadio')

class ListEstadios(ListView):
    template_name = "nfl/list_estadio.html"  
    model = Estadio
    context_object_name = 'estadios'

class DetailEstadio(DetailView):
    template_name = "nfl/detail_estadio.html"
    model = Estadio
    context_object_name = 'estadio'

class UpdateEstadio(UpdateView):
    template_name = "nfl/update_estadio.html"
    model = Estadio
    form_class = EstadioForm
    success_url = reverse_lazy('nfl:list_estadio')

class DeleteEstadio(DeleteView):
    template_name = "nfl/delete_estadio.html"
    model = Estadio
    success_url = reverse_lazy('nfl:list_estadio')

# Vistas para Duenio
class CreateDuenio(CreateView):
    template_name = "nfl/create_duenio.html"
    model = Duenio
    form_class = DuenioForm
    success_url = reverse_lazy('nfl:list_duenio')

class ListDuenios(ListView):
    template_name = "nfl/list_duenio.html"
    model = Duenio
    context_object_name = 'duenios'

class DetailDuenio(DetailView):
    template_name = "nfl/detail_duenio.html"
    model = Duenio
    context_object_name = 'duenio'

class UpdateDuenio(UpdateView):
    template_name = "nfl/update_duenio.html"
    model = Duenio
    form_class = DuenioForm
    success_url = reverse_lazy('nfl:list_duenio')

class DeleteDuenio(DeleteView):
    template_name = "nfl/delete_duenio.html"
    model = Duenio
    success_url = reverse_lazy('nfl:list_duenio')


# Vistas para Jugador
class CreateJugador(CreateView):
    template_name = "nfl/create_jugador.html"
    model = Jugador
    form_class = JugadorForm
    success_url = reverse_lazy('nfl:list_jugador')

class ListJugadores(ListView):
    template_name = "nfl/list_jugador.html"
    model = Jugador
    context_object_name = 'jugadores'

class DetailJugador(DetailView):
    template_name = "nfl/detail_jugador.html"
    model = Jugador
    context_object_name = 'jugador'

class UpdateJugador(UpdateView):
    template_name = "nfl/update_jugador.html"
    model = Jugador
    form_class = JugadorForm
    success_url = reverse_lazy('nfl:list_jugador')

class DeleteJugador(DeleteView):
    template_name = "nfl/delete_jugador.html"
    model = Jugador
    success_url = reverse_lazy('nfl:list_jugador')

remedial2/nfl/templates/base/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}NFL App{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" integrity="sha384-eGImX6CEY4pMz9Rp7Uf2L84LBjV5b2Msv71/L5e3I/rdZhqTkt4h76TEVRNhXTvc" crossorigin="anonymous">
    <style>
        body {
            background-color: #f8f9fa; 
        }

        .navbar {
            background-color: #007bff !important; 
        }

        .navbar-brand {
            font-size: 1.5em; 
        }

        .navbar-nav .nav-link {
            color: #ffffff !important; 
        }

        .navbar-nav .nav-link:hover {
            color: #ffffff; 
        }

        .btn-outline-light {
            color: #ffffff;
            border-color: #ffffff; 
        }

        .btn-outline-light:hover {
            color: #007bff;
            background-color: #ffffff; 
        }

        .text-dark {
            color: #212529 !important;
        }

        .text-light {
            color: #ffffff !important; 
        }

        footer {
            background-color: #343a40;
        }
    </style>
</head>
<body>
    <div class="container">
        <!-- NAV BAR -->
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">NFL</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'home:index' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'nfl:list_ciudades' %}">Ciudad</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'nfl:list_equipo' %}">Equipos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'nfl:list_estadio' %}">Estadios</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'nfl:list_duenio' %}">Duenios</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'nfl:list_jugador' %}">Jugadores</a>
                        </li>
                    </ul>
                    <form class="d-flex" role="search">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-light" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>

        <div class="row mt-4">
            <div class="col-12">
                {% block content %}
                {% endblock content %}
            </div>
        </div>

        <footer class="text-center text-light mt-5">
            <div class="container pt-4">
                <section class="mb-4">
                    <a class="btn btn-link btn-floating btn-lg text-light m-1" href="#!" role="button" data-mdb-ripple-color="dark">
                        <i class="fab fa-facebook-f"></i>
                    </a>
                    <a class="btn btn-link btn-floating btn-lg text-light m-1" href="#!" role="button" data-mdb-ripple-color="dark">
                        <i class="fab fa-twitter"></i>
                    </a>
                    <a class="btn btn-link btn-floating btn-lg text-light m-1" href="#!" role="button" data-mdb-ripple-color="dark">
                        <i class="fab fa-google"></i>
                    </a>
                    <a class="btn btn-link btn-floating btn-lg text-light m-1" href="#!" role="button" data-mdb-ripple-color="dark">
                        <i class="fab fa-instagram"></i>
                    </a>
                    <a class="btn btn-link btn-floating btn-lg text-light m-1" href="#!" role="button" data-mdb-ripple-color="dark">
                        <i class="fab fa-linkedin"></i>
                    </a>
                    <a class="btn btn-link btn-floating btn-lg text-light m-1" href="#!" role="button" data-mdb-ripple-color="dark">
                        <i class="fab fa-github"></i>
                    </a>
                </section>
            </div>

            <div class="text-center p-3" style="background-color: #343a40;">
                © 2023 Copyright:
                <a class="text-light" href="#">Avalos Garcia Juan Antonio</a>
            </div>
        </footer>
    </div>

    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>